import { createFileRoute, Link } from "@tanstack/react-router";
import { SiteFooter, SiteHeader } from "@/components/SiteChrome";
import shadowImg from "@/assets/shadow.jpg";

export const Route = createFileRoute("/how-it-works")({
  head: () => ({
    meta: [
      { title: "How it works & privacy — StepOut" },
      {
        name: "description",
        content:
          "How StepOut's physical CAPTCHA works, what it can and cannot verify, and what data stays on your device.",
      },
      { property: "og:title", content: "How StepOut works" },
      {
        property: "og:description",
        content: "Real-world challenges, honest verification, minimal data.",
      },
    ],
  }),
  component: HowPage,
});

const STEPS = [
  [
    "You receive a challenge",
    "A small, safe, practical task — generated by Gemma when the backend is reachable, or picked from a built-in set otherwise. Every challenge shows which source made it.",
  ],
  [
    "You leave the screen",
    "A distraction-free timer runs on timestamps, so pausing, resuming and refreshing keep the right time.",
  ],
  [
    "You come back",
    "You record what you noticed in your own words. Nothing is required except honesty.",
  ],
  [
    "StepOut records what it can",
    "In this version every completion is self-reported. StepOut never claims to have verified something it didn't.",
  ],
];

function HowPage() {
  return (
    <div>
      <SiteHeader />
      <section className="page-x">
        <div className="page-max grid gap-12 py-16 md:grid-cols-12 md:py-24">
          <div className="md:col-span-6">
            <p className="eyebrow">The method</p>
            <h1 className="display-xl mt-6">
              A human check you can only pass <em>outside.</em>
            </h1>
          </div>
          <img
            src={shadowImg}
            alt="A window's shadow stretched across wooden floorboards"
            className="aspect-[4/3] w-full object-cover md:col-span-5 md:col-start-8"
          />
        </div>
      </section>

      <section className="page-x">
        <ol className="page-max">
          {STEPS.map(([t, d], i) => (
            <li key={t} className="rule grid gap-4 py-10 md:grid-cols-12">
              <span className="numeral md:col-span-2 !text-[4rem]">
                {String(i + 1).padStart(2, "0")}
              </span>
              <h2 className="display-md md:col-span-4">{t}</h2>
              <p className="text-lg text-ink-soft md:col-span-5 md:col-start-8">{d}</p>
            </li>
          ))}
        </ol>
      </section>

      <section id="privacy" className="page-x rule mt-16">
        <div className="page-max grid gap-10 py-20 md:grid-cols-12">
          <h2 className="display-lg md:col-span-5">
            Privacy, <em>plainly.</em>
          </h2>
          <ul className="space-y-5 text-lg text-ink-soft md:col-span-6 md:col-start-7">
            <li>No account, no GPS, no camera required.</li>
            <li>Your challenges and reflections are stored only in this browser.</li>
            <li>
              When Gemma is connected, only your preferences — and, for a reflection, the challenge
              title and your written observation — are sent to the StepOut backend.
            </li>
            <li>
              No photo is collected, and nothing is labelled “verified” unless a real check
              happened.
            </li>
          </ul>
        </div>
      </section>

      <section className="page-x">
        <div className="page-max pb-10">
          <Link to="/create" className="btn-primary">
            Get a challenge ↗
          </Link>
        </div>
      </section>
      <SiteFooter />
    </div>
  );
}
