/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChallengeRouteImport } from './routes/challenge'
import { Route as CreateRouteImport } from './routes/create'
import { Route as GoRouteImport } from './routes/go'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as ResultRouteImport } from './routes/result'
import { Route as ReturnRouteImport } from './routes/return'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengeRoute = ChallengeRouteImport.update({
  id: '/challenge',
  path: '/challenge',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const GoRoute = GoRouteImport.update({
  id: '/go',
  path: '/go',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultRoute = ResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnRoute = ReturnRouteImport.update({
  id: '/return',
  path: '/return',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/challenge': typeof ChallengeRoute
  '/create': typeof CreateRoute
  '/go': typeof GoRoute
  '/how-it-works': typeof HowItWorksRoute
  '/result': typeof ResultRoute
  '/return': typeof ReturnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/challenge': typeof ChallengeRoute
  '/create': typeof CreateRoute
  '/go': typeof GoRoute
  '/how-it-works': typeof HowItWorksRoute
  '/result': typeof ResultRoute
  '/return': typeof ReturnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/challenge': typeof ChallengeRoute
  '/create': typeof CreateRoute
  '/go': typeof GoRoute
  '/how-it-works': typeof HowItWorksRoute
  '/result': typeof ResultRoute
  '/return': typeof ReturnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/challenge'
    | '/create'
    | '/go'
    | '/how-it-works'
    | '/result'
    | '/return'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/challenge'
    | '/create'
    | '/go'
    | '/how-it-works'
    | '/result'
    | '/return'
  id:
    | '__root__'
    | '/'
    | '/challenge'
    | '/create'
    | '/go'
    | '/how-it-works'
    | '/result'
    | '/return'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChallengeRoute: typeof ChallengeRoute
  CreateRoute: typeof CreateRoute
  GoRoute: typeof GoRoute
  HowItWorksRoute: typeof HowItWorksRoute
  ResultRoute: typeof ResultRoute
  ReturnRoute: typeof ReturnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenge': {
      id: '/challenge'
      path: '/challenge'
      fullPath: '/challenge'
      preLoaderRoute: typeof ChallengeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/go': {
      id: '/go'
      path: '/go'
      fullPath: '/go'
      preLoaderRoute: typeof GoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/return': {
      id: '/return'
      path: '/return'
      fullPath: '/return'
      preLoaderRoute: typeof ReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChallengeRoute: ChallengeRoute,
  CreateRoute: CreateRoute,
  GoRoute: GoRoute,
  HowItWorksRoute: HowItWorksRoute,
  ResultRoute: ResultRoute,
  ReturnRoute: ReturnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
